name: flutter_timetable
description: Displays a timetable for dates and times on items in a list.
version: 1.1.0
repository: https://github.com/yourfriendken/flutter_timetable

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
