name: flutter_timetable
description: Displays a timetable for dates and times on items in a list.
version: 1.1.0
repository: https://github.com/yourfriendken/flutter_timetable

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  kotlin_scope_function: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
